### ISSUE TITLE
Implement origin inference using identifiers.org information 

### ISSUE THREAD

**Issue by reece** [biocommons/bioutils#13]
Identifiers.org contains regexps associated with identifier syntax. For example, http://identifiers.org/insdc shows:

field | value
-- | --
Recommended name | Nucleotide Sequence Database
Alternative name(s) | International Nucleotide Sequence Database CollaborationINSDCNCBI nucleotideGenBank
Description | The International Nucleotide Sequence Database Collaboration (INSDC) consists of a joint effort to collect and disseminate databases containing DNA and RNA sequences.
Identifier pattern | ^([A-Z]\d{5}\|[A-Z]{2}\d{6}\|[A-Z]{4}\d{8}\|[A-J][A-Z]{2}\d{5})(\.\d+)?$
Registry identifier | MIR:00000029
Namespace | insdc
URI | http://identifiers.org/insdc/

Goal: implement functions to infer namespace from a given accession based on regexp matches.

Records obtained from identifiers.org should be general enough to enable implementing CURIEs (using the namespace) and resolvers (using the uri).

The registry is available at https://identifiers.org/service/registryxml

**Comment by afrubin** [comment]
Identifiers.org is a great resource but many of the regexps are overly permissive or don't handle all the special cases. For example, the mouse strain identifier prefixes are not valid according to the [Identifiers.org Ensembl entry](https://www.ebi.ac.uk/miriam/main/datatypes/MIR:00000003) (e.g. [MGP_CAROLIEiJ_G0022789](https://asia.ensembl.org/Mus_caroli/Gene/Summary?db=core;g=MGP_CAROLIEiJ_G0022789;r=19:11287323-11288346;t=MGP_CAROLIEiJ_T0048317)).

I added several genomic identifier schemes to the https://github.com/inveniosoftware/idutils package, including regexps and url resolvers. Some of these were based on Identifiers.org but most were created using each databases's documentation. Maybe this would be useful to import into `bioutils/accession.py`?

We can certainly add more schemes to idutils. So far I've only implemented the ones that were relevant to a particular project.
