### ISSUE TITLE
Write/improve documentation

### ISSUE THREAD

**Issue by reece** [biocommons/bioutils#22]
bioutils now has a proper docs directory.  Nearly all of the docs are actually pulled from the docstrings in the source files. Results are automatically built at https://bioutils.readthedocs.io. 

To build locally type `make -C docs html`, then open `docs/build/html/index.html`.

To write/improve documentation, do the following:

- [ ] Set up a linux VM
- [ ] Fork and clone this repo
- [ ] Set up environment. `make devready` ought to do it.
- [ ] Demonstrate that you can build with `make -C docs html`
- [ ] Add a comment to this issue saying that you're working on docs for a specific file
- [ ] Make changes, using `make -C html` to rebuild as necessary.
- [ ] Commit with a message like `#22: Added docs for normalize.py` (The `#22` refers to this issue and gihub will automatically create a link to it.)
- [ ] `git push`
- [ ] Submit a PR at github

N.B. bioutils.readthedocs.io won't be rebuilt until your PR is merged, so don't expect that to update immediately.

Thanks!

**Comment by trentwatt** [comment]
Have most of the documentation for other files done.
