### ISSUE TITLE
wheel build fails

### ISSUE THREAD

**Issue by marty-brandon-nih** [biocommons/bioutils#26]
A very small error in the setup.cfg file, introduced in version 0.5.0 is causing wheel builds to fail.

Here is the setup.cfg change to make:
-license-file = LICENSE
+license-file = LICENSE.txt

pip works around this issue for installations from the command-line, but it causes a problem for build chains relying on the wheel build (it breaks in AWS SAM using a docker container).

The problem can reproduced with this command:
pip wheel --wheel-dir wheels/bioutils/ bioutils==0.5.0

While the wheel build for the previous version works fine:
pip wheel --wheel-dir wheels/bioutils/ bioutils==0.4.4

**Comment by reece** [comment]
@marty-brandon-nih Thanks for the report and the fix. Change has already landed at PyPI as 0.5.1 and I verified with `pip wheel --wheel-dir wheels/bioutils/ bioutils==0.5.1`.

**Comment by marty-brandon-nih** [comment]
Wow, so quick!  Thank you.  Can confirm that it works when pip builds the wheel using the latest PyPI release.
