### ISSUE TITLE
release latest main branch

### ISSUE THREAD

**Issue by andreasprlic** [biocommons/bioutils#42]
Hi Reece,

I haven't see a release of bioutils since about a year ago. What is needed to get a new release out? Let me know if I can help with that.

Thanks,
Andreas

**Comment by reece** [comment]
All of the CI/CD was tied to travis. We need to migrate to github actions. That shouldn't be hard. I'll take a stab now and check back in a couple of hours.

**Comment by reece** [comment]
'tis done!
0.5.6 was released to https://pypi.org/project/bioutils/.
Changelog at https://bioutils.readthedocs.io/en/latest/changelog/0.5/0.5.6.html

Even better, this github action should work on other biocommons packages.
