### ISSUE TITLE
Add GRCh38p13 and GRCh38p14

### ISSUE THREAD

**Issue by davmlaw** [biocommons/bioutils#54]
Hi, could you please add the last 2 GRCh38 patches thanks?

[GRCh38.p13](https://www.ncbi.nlm.nih.gov/assembly/GCF_000001405.39/)

```
make_ac_name_map("GRCh38.p13")
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.10/dist-packages/bioutils/_data/assemblies/GRCh38.p13.json.gz'
```

[GRCh38.p14](https://www.ncbi.nlm.nih.gov/assembly/GCF_000001405.40/)

```
make_ac_name_map("GRCh38.p14")
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.10/dist-packages/bioutils/_data/assemblies/GRCh38.p14.json.gz'
```

**Comment by reece** [comment]
Closed with #45. Now available as 0.5.8 at https://pypi.org/project/bioutils/.
